// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGF7h9-feAUaHFS19jf8oW0W5Byucf4pI',
    appId: '1:877481415536:web:f78cb14c492abafa74b5b5',
    messagingSenderId: '877481415536',
    projectId: 'my-task-app-ef5e8',
    authDomain: 'my-task-app-ef5e8.firebaseapp.com',
    storageBucket: 'my-task-app-ef5e8.firebasestorage.app',
    measurementId: 'G-CXQ2X214Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSxdkwo2G8vS_guAYSTvilXvm0IxDi5E',
    appId: '1:877481415536:android:2b5a86d9b6f2930274b5b5',
    messagingSenderId: '877481415536',
    projectId: 'my-task-app-ef5e8',
    storageBucket: 'my-task-app-ef5e8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR1F8s0OBbepnw0yWeJoIN3fxHCY5KCOQ',
    appId: '1:877481415536:ios:ac270c65799da39d74b5b5',
    messagingSenderId: '877481415536',
    projectId: 'my-task-app-ef5e8',
    storageBucket: 'my-task-app-ef5e8.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR1F8s0OBbepnw0yWeJoIN3fxHCY5KCOQ',
    appId: '1:877481415536:ios:ac270c65799da39d74b5b5',
    messagingSenderId: '877481415536',
    projectId: 'my-task-app-ef5e8',
    storageBucket: 'my-task-app-ef5e8.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGF7h9-feAUaHFS19jf8oW0W5Byucf4pI',
    appId: '1:877481415536:web:5efac7078be366bb74b5b5',
    messagingSenderId: '877481415536',
    projectId: 'my-task-app-ef5e8',
    authDomain: 'my-task-app-ef5e8.firebaseapp.com',
    storageBucket: 'my-task-app-ef5e8.firebasestorage.app',
    measurementId: 'G-2SK6K23GQH',
  );
}
